package com.example.email.client;

import java.util.concurrent.Future;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

import com.example.email.client.type.SendResponse;
/*
import javax.jws.soap.SOAPBinding;
*/

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-02-25T13:38:01.854+01:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://prosodie.com/ws/email/", name = "Email")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED)

public interface Email
{


    @RequestWrapper(localName = "send", targetNamespace = "http://prosodie.com/ws/email/type", className = "com.example.email.client.type.Send")
    @ResponseWrapper(localName = "sendResponse", targetNamespace = "http://prosodie.com/ws/email/type", className = "com.example.email.client.type.SendResponse")
    @WebMethod(operationName = "send")
    public Response<SendResponse> sendAsync
    (
        @WebParam(/*partName = "parameters", */name = "requestType", targetNamespace = "http://prosodie.com/ws/email/type")
        String requestType
    );

 
    @RequestWrapper(localName = "send", targetNamespace = "http://prosodie.com/ws/email/type", className = "com.example.email.client.type.Send")
    @ResponseWrapper(localName = "sendResponse", targetNamespace = "http://prosodie.com/ws/email/type", className = "com.example.email.client.type.SendResponse")
    @WebMethod(operationName = "send")
    public Future<?> sendAsync
    (
        @WebParam(/*partName = "parameters", */name = "requestType", targetNamespace = "http://prosodie.com/ws/email/type")
        String requestType,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SendResponse> asyncHandler
    );


    @RequestWrapper(localName = "send", targetNamespace = "http://prosodie.com/ws/email/type", className = "com.example.email.client.type.Send")
    @ResponseWrapper(localName = "sendResponse", targetNamespace = "http://prosodie.com/ws/email/type", className = "com.example.email.client.type.SendResponse")
    @WebResult(/*partName = "parameters", */name = "responseType", targetNamespace = "http://prosodie.com/ws/email/type")
    @WebMethod
    public String send
    (
        @WebParam(/*partName = "parameters",*/name = "requestType", targetNamespace = "http://prosodie.com/ws/email/type")
        String requestType
    );
}

/*
 * <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://prosodie.com/ws/email/" version="1.0">
<xs:complexType name="send">
    <xs:sequence>
      <xs:element minOccurs="0" name="requestType" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="sendResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="responseType" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns0="http://prosodie.com/ws/email/" xmlns:tns="http://prosodie.com/ws/email/type" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://prosodie.com/ws/email/type">
  <xsd:element name="send" nillable="true" type="ns0:send"/>
  <xsd:element name="sendResponse" nillable="true" type="ns0:sendResponse"/>
</xsd:schema>
  </wsdl:types>
  <wsdl:message name="sendResponse">
    <wsdl:part name="parameters" element="ns1:sendResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="send">
    <wsdl:part name="parameters" element="ns1:send">
    </wsdl:part>
  </wsdl:message>

<wsdl:portType name="Email">
    <wsdl:operation name="send">
      <wsdl:input name="send" message="tns:send">
    </wsdl:input>
      <wsdl:output name="sendResponse" message="tns:sendResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>

<wsdl:binding name="EmailServiceSoapBinding" type="tns:Email">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="send">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="send">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="sendResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="EmailService">
    <wsdl:port name="EmailPort" binding="tns:EmailServiceSoapBinding">
      <soap:address location="http://localhost:9090/EmailPort"/>
    </wsdl:port>
  </wsdl:service>
*/