package com.example.email.client;

import java.util.concurrent.Future;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

import com.example.email.client.type.EmailRequest;
import com.example.email.client.type.EmailResponse;
import com.example.email.client.type.EmailResponseWrapper;



/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-02-25T13:38:01.854+01:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://prosodie.com/ws/email/", name = "Email")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED)

public interface Email
{


	@RequestWrapper(localName  = "emailWrapper", targetNamespace = "http://prosodie.com/ws/email/type", className = "com.example.email.client.type.EmailWrapper")
    @ResponseWrapper(localName = "emailResponseWrapper", targetNamespace = "http://prosodie.com/ws/email/type", className = "com.example.email.client.type.EmailResponseWrapper")
    @WebMethod(operationName = "send")
    public Response<EmailResponseWrapper> sendAsync
    (
    	@WebParam(name = "emailRequest", targetNamespace = "http://prosodie.com/ws/email/type")
    	EmailRequest emailRequest
    );

 
	@RequestWrapper(localName  = "emailWrapper", targetNamespace = "http://prosodie.com/ws/email/type", className = "com.example.email.client.type.EmailWrapper")
    @ResponseWrapper(localName = "emailResponseWrapper", targetNamespace = "http://prosodie.com/ws/email/type", className = "com.example.email.client.type.EmailResponseWrapper")
    @WebMethod(operationName = "send")
    public Future<?> sendAsync
    (
    	@WebParam(name = "emailRequest", targetNamespace = "http://prosodie.com/ws/email/type")
    	EmailRequest emailRequest,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<EmailResponseWrapper> asyncHandler
    );


    @RequestWrapper(localName  = "emailWrapper", targetNamespace = "http://prosodie.com/ws/email/type", className = "com.example.email.client.type.EmailWrapper")
    @ResponseWrapper(localName = "emailResponseWrapper", targetNamespace = "http://prosodie.com/ws/email/type", className = "com.example.email.client.type.EmailResponseWrapper")
    @WebResult(name = "emailResponse", targetNamespace = "http://prosodie.com/ws/email/type")
    @WebMethod
    public EmailResponse send
    (
        @WebParam(name = "emailRequest", targetNamespace = "http://prosodie.com/ws/email/type")
        EmailRequest emailRequest
    );
}

